
# Tool of choice is UV, but this might be compatible with Poetry as well

[project]
name = "ha-scene-tracker"
version = "0.1.0"
description = "Home Assistant custom component for tracking and toggling active scenes."
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = []

[project.optional-dependencies]
dev = [
    "homeassistant>=2026",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = false
